// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDdGv-SGIlpc4KzaKoJAIdtgcEWGrt1Hk',
    appId: '1:149872191226:web:45644b8a0cffbc1a088b43',
    messagingSenderId: '149872191226',
    projectId: 'gctu-7fb3a',
    authDomain: 'gctu-7fb3a.firebaseapp.com',
    storageBucket: 'gctu-7fb3a.appspot.com',
    measurementId: 'G-BJQFMHCZXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJvKWwEDaiH-GRc9rDgWBV2keNON4Q5A',
    appId: '1:149872191226:android:37af816c61229490088b43',
    messagingSenderId: '149872191226',
    projectId: 'gctu-7fb3a',
    storageBucket: 'gctu-7fb3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7bvPv2RcGZF0T0hLt4TP5QYmZLiuutno',
    appId: '1:149872191226:ios:c633424e9147555b088b43',
    messagingSenderId: '149872191226',
    projectId: 'gctu-7fb3a',
    storageBucket: 'gctu-7fb3a.appspot.com',
    iosClientId: '149872191226-2vkn7oqd75d5754o3tme7inagt50hbkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gctuStudents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7bvPv2RcGZF0T0hLt4TP5QYmZLiuutno',
    appId: '1:149872191226:ios:c633424e9147555b088b43',
    messagingSenderId: '149872191226',
    projectId: 'gctu-7fb3a',
    storageBucket: 'gctu-7fb3a.appspot.com',
    iosClientId: '149872191226-2vkn7oqd75d5754o3tme7inagt50hbkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gctuStudents',
  );
}
